language: ruby
rvm:
  - 2.2.5
  - 2.3.1
  - ruby-head
gemfile:
  - gemfiles/rouge_1.gemfile
  - gemfiles/rouge_2.gemfile
branches:
  only:
    - "master"
    - "/^release-/"
before_install: gem install bundler
matrix:
  fast_finish: true
  include:
    - rvm: jruby-9.0.5.0
      env: DISABLE_NOKOGIRI=1
    - rvm: jruby-9.0.5.0
      env: DISABLE_NOKOGIRI=0
  allow_failures:
    - rvm: jruby-9.0.5.0
      env: DISABLE_NOKOGIRI=1
    - rvm: jruby-9.0.5.0
      env: DISABLE_NOKOGIRI=0
    - rvm: ruby-head
cache: bundler
sudo: false
git:
  depth: 10
